### PR TITLE
memory issues + syntax fixed

### PR DESCRIPTION
**Pull request by cyfung1031**
changes:

1. replace all `var` to `let` to avoid typo become runtime errors.
2. changed some function to arrow function to avoid `.bind(this)`

> 
> you have been using the methods appeared after `let` and "arrow function", such as `prepend`.
> So those who can run your script without translation can also use `let` and "arrow function"
> 
> using `let` can avoid the typo mistake runtime errors.
> using `arrow function` can avoid `.bind(this)`
> 
> P.S. you have already used some arrow functions like `if (subAliases.some(subAlias => subAlias.includes(prop))) {` and `let nestedFunction = subAliases.find(element => element.includes('.')).split('.')[1];`
> 

3. organized some function inside for-loop, while-loop, and setTimeout into better manner to avoid memory leakage. (nested functions)
4. and also minor fixs.

The existing script uses `document.head.prepend` which is the newest one in this js file.
So all of your users can also use `let`, `arrow`, etc. 

There can be more simplifications such as `activate: function(interval) {` into `activate(interval) {` and `'↻ ChatGPT >> [' + autoRefresh.nowTimeStamp() + '] ChatGPT session refreshed'` to \` `'↻ ChatGPT >> [${ autoRefresh.nowTimeStamp() }] ChatGPT session refreshed` \`, but these does not affect performance.

### CODE REVIEW

**Comment by adamlui** [comment]
sup @cyfung1031 I originally wanted to avoid ES6 (arrow, non-`var`) for max compatibility, but since then, I added `chatgpt.isIdle()` which relies on promise so ES6 is ok now I guess, but have you tested your changes to work? if so I'll merge

**Comment by adamlui** [comment]
@cyfung1031 ...but if you have an ES5 method for `chatgpt.isIdle()` then avoiding ES6 is best (it is quite new in JS age and many users have old browsers)

**Comment by adamlui** [comment]
@cyfung1031 also is there reason to break out `timerFunctionScheduleRefresh()` because it is only used in code once?

**Comment by adamlui** [comment]
@cyfung1031 also is there a reason to make the `// Create chatgpt.[actions]Button(identifier) functions` routine longer? And to define another function that's only used once in the code?

**Review by adamlui — CHANGES_REQUESTED** [review]
@cyfung1031 I asked ChatGPT and indeed your changes to the function & alias generation routines can avoid memory leaks, so they are great! Can you fix the ESLint issues and i will merge asap?

**Comment by cyfung1031** [comment]
> 

Um.. if you want the whole coding before compression become es5
You need to really think about those arrow functions for looping.  

Actually you can still code in es6 and then let js compressor to handle to change into es5

Go back to your question to me.
If you dont use Promise,  then go back to the basics of javasctipt,  which is event.

When it is idle,  dispatchEvent to your EventTarget
Then you can use EventTarget.addEventListener  to monitor such event

**Comment by adamlui** [comment]
> Um.. if you want the whole coding before compression become es5 You need to really think about those arrow functions for looping.

I know arrows are es6, I'm saying I won't convert them unless `chatgpt.isIdle()` can be made so too

> Actually you can still code in es6 and then let js compressor to handle to change into es5

What compressor will change this to es5?

> Go back to your question to me. If you dont use Promise, then go back to the basics of javasctipt, which is event. When it is idle, dispatchEvent to your EventTarget Then you can use EventTarget.addEventListener to monitor such event

So can you do or no?

**Comment by cyfung1031** [comment]
changing `chatgpt.isIdle()` is meaningless. I won't do. Just keep everything ES6.

**Comment by adamlui** [comment]
@cyfung1031 wdym meaningless, I just told you the meaning: it is a benefit to avoid ES6. (Just because you like it doesn't mean everyone uses it, by avoiding then users increase compatiblity and gain more users that way)

**Comment by adamlui** [comment]
@cyfung1031 I reverted your pull request of minimal contributions btw because it has become clear from your comments here and by criticizing the helpful Hindi contributor's translation of license you were actually investigating it to add yourself as copyright holder, thus focused on gaining fame instead of concern over end users (otherwise you would not call benefits to them "meaningless") so you are not a good fit for this project as a self-promoter instead of caring for others

**Pull request merged**
