### PR TITLE
fix regenerate button click not firing

### PR DESCRIPTION
**Pull request by meiraleal**

### CODE REVIEW

**Comment by adamlui** [comment]
Thanks @meiraleal !

**Comment by adamlui** [comment]
@meiraleal did you find this from the Product Hunt [launch](https://www.producthunt.com/posts/chatgpt-js)? (If so I can add you as maker on there if you share your username)

**Comment by meiraleal** [comment]
hi adam! No, I found it here on github but I will check it in the product hunt, very cool! my username there is acmeira1

Thanks for the lib, very helpful!

**Comment by adamlui** [comment]
Nice I just added you as maker!

Screenshot_2023-06-29-14-44-24-03_3aea4af51f236e4932235fdada7d1643

Also if you want to share what you made whenever I would love to check it out!

**Pull request merged**
